# Generated by Django 4.1.7 on 2025-04-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPriceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bitcoin Price Cache',
                'verbose_name_plural': 'Bitcoin Price Caches',
            },
        ),
    ]
